#! /bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="ben@blowery.org"
export FULLNAME="Ben Lowery"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

#export GIT_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$EMAIL
#export GIT_COMMITTER_EMAIL=$EMAIL

export MANWIDTH=80
export EDITOR="emacs -nw"
export VISUAL="emacs -nw"
#export CCACHE_DIR=$HOME/.ccache

export LC_MESSAGES=C
export LC_ALL=

PATH="/home/blowery/bin:$PATH"
export PATH

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
